__tests__/index.js, index.js
Add `getCache` to get the internal cache, `clearCache` for clearing the
entire cache and `removeCacheKey` for removing a cache key.
=> Expose cache methods

index.d.ts
Fixes https://github.com/toomuchdesign/re-reselect/issues/15
=> updated OutputParametricCachedSelector definition

README.md
Hey, a small correction to the example in readme :)
=> Add missing commas to `getPieceOfData` example

.gitignore, .lintstagedrc, package-lock.json, package.json
Chores
Some  dev-dependencies rely on packages considered vulnerable by GitHub's security tools.
Update dev dependencies to latest release.
No
=> Update dev dependencies

package-lock.json, package.json, src/__tests__/index.spec.js, src/index.d.ts, src/index.js, typescript_test/test.ts
feature
recomputations and dependencies not impelemented
supported recomputations and dependencies
see https://github.com/reduxjs/reselect/releases/tag/v4.0.0
I think so, because the reselect for similar changes made it.
see conversation in #60
=> Reselect v4 features

README.md
Docs
Add "about re-reselect" section to docs.
No
=> Add "about re-reselect" section to docs

package-lock.json
=> Dedupe lock file

.all-contributorsrc, CHANGELOG.md, README.md, src/cache/README.md
=> Update v3.2.0 docs

.travis.yml, jest/__snapshots__/bundles-snapshot.test.js.snap, jest/bundles-snapshot.test.js, package.json
Bundle tests update
When updating bundling dependencies there's no way to spot possible changes introduced by the new packages versions (event though bundles are also unit tested).
Add a snapshot test targeting one of the bundles (dist).
No
=> Prepare for renovate and extend bundle tests

jest/__snapshots__/bundles-snapshot.test.js.snap, package-lock.json, package.json, rollup.config.js
Dev dependencies update
Update Rollup to V1.16.x
No (compiled UMD syntax was slightly changed, but I expect rollup to be solid about this)
=> Rollup update

README.md, examples/4-programmatic-keyselector-composition.md
Docs update
Renew/rephrase readme
No
=> Revamp docs

README.md
Docs update
Wrong resultFunc/keySelector arguments 🤭
=> Fix documentation examples

README.md, examples/1-join-selectors.md, examples/2-avoid-selector-factories.md, examples/3-cache-api-calls.md, examples/4-programmatic-keyselector-composition.md, src/cache/README.md
- Typo fixes across the documentation and example files for `re-reselect`.
- Fix relative links for cache resources
n/a: no open issues. 
- Improved documentation clarity
- No breaking changes; all tests continue to pass. 
- Recently familiarized myself with the re-reselect documentation and took the opportunity to fix typos as I came across them for the project's repo.
=> [docs] Typo Fixes, Update Relative Links

README.md, examples/5-selectorator.md
=> Add selectorator docs

CHANGELOG.md
Docs update for v4.0.0
...
...
...
=> V4.0.0 docs update

src/cache/README.md
=> Fixed cache README link to FifoMapCache.js

package-lock.json, package.json, src/__tests__/createCachedSelector.test.js, src/__tests__/createStructuredCachedSelector.test.js, src/typescript_tests/cache.test.ts, src/typescript_tests/createCachedSelector.test.ts, src/typescript_tests/createStructuredCachedSelector.test.ts, tsconfig.json
Bug fix
Old TS type definition testing tools rely on old TS versions
Test TS type defs with plain typescript
No
=> test: test types definitions with plain typescript

.github/workflows/ci.yml, package-lock.json, package.json
=> chore: replace husky with simple-git-hooks

renovate.json
=> chore: update renovate/jest config

README.md
=> docs: add reselect v5 note

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/dependabot-auto-merge.yml
=> chore: update gh actions
